#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.renderers.default = "browser"
import plotly.graph_objects as go
import urllib.request
import urllib.error
###------------------Scrapping----------------------
#Le but est de créer une base de données avec toutes les infos nécessaires sur une zone particulière
#ça se décompose en plusieurs étapes
#1) On identifie la zone (latitude et longitude) 
#2) On crée une base de données avec chacun des points dans lesquels on va récolter les données à partir du site
#3) On fait la récolte de données

#1 + 2) identification de la zone




def zone(latitude_1,latitude_2,longitude_1, longitude_2, precision):
    """On entre les latitudes et la longitudes qui permettent de définir la zone dans laquelle on récoltera les données
        On renvoie un df avec chacun des points considérés"""
    startyear = 2016
    endyear = 2016
    #time= "20150105:1110"
    
    
    df = pd.DataFrame(columns = ["latitude","longitude"])
    temp = pd.DataFrame(columns = ["latitude","longitude","time","G(i)","H_sun","T2m","WS10m","Int"])
    for latitude in range(latitude_1,(latitude_2+precision),precision):
        for longitude in range(longitude_1, (longitude_2+precision), precision):
            
            try :  
                
                req = "https://re.jrc.ec.europa.eu/api/seriescalc?lat="+str(latitude)+"&lon="+str(longitude)+"&startyear="+str(startyear)+"&endyear="+str(endyear)+"&month=0&showtemperatures=1&outputformat=csv&browser=1"
                url = urllib.request.urlopen(req) 
                pomme = pd.read_csv(url,skiprows=(8),skipfooter=9,engine='python')
                pomme = pomme.loc[pomme['time'].str.endswith('05:1110') == True].values.tolist()
                pomme = [x for elem in pomme for x in elem]
                #print("POMME", pomme)
                
                
            except urllib.error.HTTPError:     
                pomme =[np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]
                
                
            #url = "https://re.jrc.ec.europa.eu/api/seriescalc?lat=45&lon=8&startyear=2015&endyear=2016&month=0&showtemperatures=1&outputformat=csv&browser=1"
            
            
            # df = df.append({"latitude": latitude,
            #                 "longitude": longitude
            #                 },
            #                 ignore_index=True)
            try: 
                temp = temp.append({"latitude": latitude,
                                "longitude": longitude,
                                "time":pomme[0],
                                "G(i)":pomme[1],
                                "H_sun":pomme[2],
                                "T2m":pomme[3],
                                "WS10m":pomme[4],
                                "Int":pomme[5]
                                },
                                ignore_index=True)
            except:
                temp = temp
            #print(temp)
            df_final = temp
            
    return df_final

df = zone(40,50,-1,5,1)
df["size"] = pd.Series([50 for x in range(len(df.index))])
import plotly.express as px

# fig = px.density_mapbox(df, lat='latitude', lon='longitude', z='G(i)', radius=30,
#                         center=dict(lat=0, lon=180), zoom=0,
#                         mapbox_style="carto-positron")
# fig.show()
fig = px.scatter_mapbox(df.dropna(), lat="latitude", lon="longitude", color="G(i)", 
                        size ="size",
                        mapbox_style="carto-positron",color_continuous_scale=[[0, 'green'], [0.25, 'yellow'], [0.5, 'orange'], [0.75, 'pink'] ,[1.0, 'red']])
fig.show()

# fig = go.Figure(go.Scattermapbox(
#     fill = "toself",
#     lon = df["longitude"] , lat = df["latitude"],
#     marker = { 'size': 30, 'color': df["G(i)"] }))
# fig.show()



